name: Format

permissions:
  contents: write

env:
  LLVM_VERSION: 16

on:
  workflow_call:
    inputs:
      zig-version:
        type: string
        required: true

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            src
            packages
            test
            bench
      - name: Setup Bun
        uses: ./.github/actions/setup-bun
        with:
          bun-version: "1.0.21"
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@c7b6cdd3adba8f8b96984640ff172c37c93f73ee
        with:
          version: ${{ inputs.zig-version }}
      - name: Install Dependencies
        run: |
          bun install
      - name: Format
        run: |
          bun fmt
      - name: Format Zig
        run: |
          bun fmt:zig
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply formatting changes

  format-cpp:
    name: format C++
    runs-on: ${{ github.repository_owner == 'oven-sh' && 'namespace-profile-bun-ci-darwin-aarch64' || 'macos-12' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Bun
        uses: ./.github/actions/setup-bun
        with:
          bun-version: latest
      - name: Install Dependencies
        env:
          HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
          HOMEBREW_NO_AUTO_UPDATE: 1
          HOMEBREW_NO_INSTALL_CLEANUP: 1
        run: |
          brew install \
            llvm@${{ env.LLVM_VERSION }} \
            ninja \
            coreutils \
            openssl@1.1 \
            libiconv \
            cmake \
            gnu-sed --force --overwrite
          echo "$(brew --prefix coreutils)/libexec/gnubin" >> $GITHUB_PATH
          echo "$(brew --prefix llvm@$LLVM_VERSION)/bin" >> $GITHUB_PATH
          brew link --overwrite llvm@$LLVM_VERSION
      - name: Bun install
        run: |
          bun install
      - name: Format
        env:
          CPU_TARGET: native
        run: |
          bun build:tidy
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply formatting changes
